# Generated by Django 4.2.4 on 2023-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('phonographicLabel', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
