# Generated by Django 4.2.4 on 2023-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='disc',
            name='artist',
            field=models.ManyToManyField(to='discos.artist'),
        ),
    ]
