# Generated by Django 4.2.4 on 2023-10-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0002_artist_disc_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonographicLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='disc',
            name='phonographicLabel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discos.phonographiclabel'),
        ),
    ]
