# Generated by Django 4.2.4 on 2023-10-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0003_phonographiclabel_alter_disc_phonographiclabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonographiclabel',
            name='phonographicLabel_name',
            field=models.CharField(default='vazio', max_length=50),
        ),
    ]
