# Generated by Django 4.2.4 on 2023-10-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0004_phonographiclabel_phonographiclabel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='phonographicLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.phonographiclabel'),
        ),
    ]
